"""aicoder init wizard — guided first-run setup."""
from __future__ import annotations
from pathlib import Path
from rich.console import Console
from rich.panel import Panel
from rich.prompt import Confirm, Prompt

console = Console()

_PROVIDERS = {
    "1": ("deepseek",   "DEEPSEEK_API_KEY",  "DeepSeek (fast, cheap — recommended default)"),
    "2": ("openai",     "OPENAI_API_KEY",     "OpenAI (GPT-4o / GPT-4-turbo)"),
    "3": ("anthropic",  "ANTHROPIC_API_KEY",  "Anthropic (Claude 3.5 Sonnet)"),
    "4": ("gemini",     "GOOGLE_API_KEY",     "Google Gemini"),
    "5": ("ollama",     None,                 "Ollama (local, no API key needed)"),
    "6": ("enterprise", None,                 "Enterprise / on-premise LLM"),
}

_TEMPLATE = """\
# AICoder configuration — generated by `aicoder init`
provider: {provider}
agent:
  max_retries: 3
  temperature: 0.1
  max_tokens: 4096
  interactive: {interactive}
max_cost_usd: {max_cost}
"""

def run_wizard(target_dir: Path | None = None) -> None:
    target_dir = (target_dir or Path(".")).resolve()
    config_path = target_dir / ".aicoder.yml"
    console.print(Panel(
        "[bold cyan]Welcome to AICoder![/bold cyan]\n\nThis short wizard will create a [bold].aicoder.yml[/bold] config file.\n[dim]Press Ctrl+C to cancel.[/dim]",
        title="��  AICoder Init", border_style="cyan",
    ))
    if config_path.exists():
        if not Confirm.ask(f"\n[yellow]⚠️  {config_path} already exists. Overwrite?[/yellow]", default=False):
            console.print("[dim]Aborted — existing config kept.[/dim]")
            return
    console.print("\n[bold]Step 1 of 3 — Choose your LLM provider[/bold]")
    for key, (_, _, label) in _PROVIDERS.items():
        console.print(f"  [cyan]{key}[/cyan]  {label}")
    while True:
        choice = Prompt.ask("\nProvider number", default="1").strip()
        if choice in _PROVIDERS:
            break
        console.print("[red]Please enter a number from 1 to 6.[/red]")
    provider, env_var, provider_label = _PROVIDERS[choice]
    console.print(f"\n[green]✓[/green]  Selected: [bold]{provider_label}[/bold]")
    api_key = None
    if env_var:
        import os
        existing_key = os.environ.get(env_var, "")
        console.print(f"\n[bold]Step 2 of 3 — API Key[/bold]")
        if existing_key:
            console.print(f"[green]✓[/green]  {env_var} is already set in your environment.")
            api_key = existing_key if Confirm.ask("  Store it in .aicoder.yml as well? (less secure)", default=False) else None
        else:
            api_key = Prompt.ask(f"  {env_var}", default="", password=True).strip() or None
    else:
        console.print(f"\n[bold]Step 2 of 3 — API Key[/bold]\n[dim]No API key needed for {provider}.[/dim]")
    console.print("\n[bold]Step 3 of 3 — Preferences[/bold]")
    interactive_mode = Confirm.ask("  Enable interactive diff approval by default?", default=True)
    try:
        max_cost = float(Prompt.ask("  Abort if cost > (USD, 0=no limit)", default="2.00").strip())
    except ValueError:
        max_cost = 2.00
    yml = _TEMPLATE.format(provider=provider, interactive=str(interactive_mode).lower(), max_cost=max_cost)
    if api_key and env_var:
        yml += f'\n{env_var.lower()}: "{api_key}"\n'
    config_path.write_text(yml)
    console.print(Panel(f"[green]✅  Config written to:[/green] [bold]{config_path}[/bold]", title="🎉  Setup Complete", border_style="green"))
